openapi: 3.0.0
info:
  title: Todo List API
  description: A simple API for managing todos.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/todos:
    get:
      summary: Retrieve a list of todos
      parameters:
        - name: search
          in: query
          description: Search term for filtering todos
          required: false
          schema:
            type: string
        - name: date
          in: query
          description: Filter todos by date of last update
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "1677152000000"
                    text:
                      type: string
                      example: "Learn Node.js"
                    completed:
                      type: boolean
                      example: false
                    createdAt:
                      type: string
                      format: date-time
                      example: "2024-07-30T12:00:00Z"
                    updatedAt:
                      type: string
                      format: date-time
                      example: "2024-07-30T12:00:00Z"
    post:
      summary: Add a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: "Learn Node.js"
      responses:
        '201':
          description: Todo successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  text:
                    type: string
                  completed:
                    type: boolean
                  createdAt:
                    type: string
                    format: date-time
                  updatedAt:
                    type: string
                    format: date-time
  /api/todos/{id}:
    put:
      summary: Update an existing todo
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the todo to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '200':
          description: Todo successfully updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  text:
                    type: string
                  completed:
                    type: boolean
                  createdAt:
                    type: string
                    format: date-time
                  updatedAt:
                    type: string
                    format: date-time
    delete:
      summary: Delete a todo
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the todo to delete
          schema:
            type: string
      responses:
        '204':
          description: Todo successfully deleted
    patch:
      summary: Mark a todo as completed
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the todo to mark as done
          schema:
            type: string
      responses:
        '200':
          description: Todo successfully marked as completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  text:
                    type: string
                  completed:
                    type: boolean
                  createdAt:
                    type: string
                    format: date-time
                  updatedAt:
                    type: string
                    format: date-time
